USE [master]
GO
/****** Object:  Database [MVVMLoginDb]    Script Date: 15/11/2022 22:19:50 ******/
CREATE DATABASE [MVVMLoginDb]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'MVVMLoginDb', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\MVVMLoginDb.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'MVVMLoginDb_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\MVVMLoginDb_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [MVVMLoginDb] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [MVVMLoginDb].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [MVVMLoginDb] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [MVVMLoginDb] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [MVVMLoginDb] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [MVVMLoginDb] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [MVVMLoginDb] SET ARITHABORT OFF 
GO
ALTER DATABASE [MVVMLoginDb] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [MVVMLoginDb] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [MVVMLoginDb] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [MVVMLoginDb] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [MVVMLoginDb] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [MVVMLoginDb] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [MVVMLoginDb] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [MVVMLoginDb] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [MVVMLoginDb] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [MVVMLoginDb] SET  ENABLE_BROKER 
GO
ALTER DATABASE [MVVMLoginDb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [MVVMLoginDb] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [MVVMLoginDb] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [MVVMLoginDb] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [MVVMLoginDb] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [MVVMLoginDb] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [MVVMLoginDb] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [MVVMLoginDb] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [MVVMLoginDb] SET  MULTI_USER 
GO
ALTER DATABASE [MVVMLoginDb] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [MVVMLoginDb] SET DB_CHAINING OFF 
GO
ALTER DATABASE [MVVMLoginDb] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [MVVMLoginDb] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [MVVMLoginDb] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [MVVMLoginDb] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [MVVMLoginDb] SET QUERY_STORE = OFF
GO
USE [MVVMLoginDb]
GO
/****** Object:  Table [dbo].[User]    Script Date: 15/11/2022 22:19:51 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[User](
	[Id] [uniqueidentifier] NOT NULL,
	[Username] [nvarchar](50) NOT NULL,
	[Password] [nvarchar](100) NOT NULL,
	[Name] [nvarchar](50) NOT NULL,
	[LastName] [nvarchar](50) NOT NULL,
	[Email] [nvarchar](100) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[Username] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[Email] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[User] ADD  DEFAULT (newid()) FOR [Id]
GO
USE [master]
GO
ALTER DATABASE [MVVMLoginDb] SET  READ_WRITE 
GO
